- type: entity
  id: NTRCrateSpesosSmall
  parent: CratePrivateSecure
  name: "Бонусний грант спесо"
  description: "Важкі часи вимагають капіталістичних рішень."
  components:
  - type: StorageFill
    contents:
      - id: SpaceCash500
        amount: 20 # Why? cuz a whole ass crate for 1 cash stack is wierd

- type: entity
  id: NTRCratePointDisks
  parent: CrateScienceSecure
  name: "Бонусні диски з очками"
  description: "Прогрес, мій друже, прогрес."
  components:
  - type: StorageFill
    contents:
      - id: ResearchDisk
        amount: 10 # 10 x 1000 = 10000 points, should be enough for sci, and also, a whole crate for 1 disk is stupid so 10 disks is good

- type: entity
  id: NTRCrateEmergencyMed
  parent: CrateMedicalSecure
  name: "Невідкладні медичні засоби"
  description: "Подумайте, як би ви це пояснили NT."
  components:
  - type: StorageFill
    contents:
      - id: MedkitBurnFilled
      - id: MedkitToxinFilled
      - id: MedkitOxygenFilled
      - id: MedkitBruteFilled
      - id: MedkitRadiationFilled # its an emergency med crate, not war med crate so no combat medkits

- type: entity
  id: NTRCrateDisablers
  parent: CrateCommandSecure
  name: "Ящик з дестабілізаторами"
  description: "Ящик з дестабілізаторами, навіщо вам це?"
  components:
  - type: StorageFill
    contents:
      - id: WeaponDisablerSMG # yknow maybe its too good for tier 1, i hope i dont forget about this before doing a pr
      - id: WeaponDisabler
        amount: 3

- type: entity
  id: NTRCrateToolsSmall
  parent: CrateEngineeringSecure
  name: "Ящик з інструментами"
  description: "Ящик зі стандартними інструментами NanoTrasen."
  components:
  - type: StorageFill
    contents:
      - id: Wirecutter
      - id: Screwdriver
      - id: Wrench
      - id: Multitool
      - id: NetworkConfigurator
      - id: ClothingBeltUtility
      - id: Crowbar

- type: entity
  id: NTRBoardTelecom
  parent: CrateCommandSecure
  name: "Ящик з платами для телеком-сервера"
  description: "Ящик, що містить 2 плати для телеком-сервера."
  components:
  - type: StorageFill
    contents:
    - id: TelecomServerCircuitboard
    - id: TelecomServerCircuitboard

- type: entity
  id: NTRBoardHolopad
  parent: CrateCommandSecure
  name: "Ящик з голопадами"
  description: "Ящик, що містить 2 плати для голопада."
  components:
  - type: StorageFill
    contents:
    - id: HolopadMachineCircuitboard
    - id: HolopadMachineCircuitboard # what is the point of having 1 holopad?

- type: entity
  id: NTRBoardShuttle
  parent: CrateEngineeringSecure
  name: "Ящик з комплектом для створення шатла"
  components:
  - type: StorageFill
    contents:
    - id: ThrusterFlatpack
      amount: 4
    - id: ShuttleConsoleCircuitboard
    - id: GyroscopeFlatpack
