# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 RatherUncreative <RatherUncreativeName@proton.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  name: "дивні ягоди"
  parent: FoodProduceBase
  id: FoodStrangeBerries
  description: "Жменя дивних ягід."
  components:
  - type: FlavorProfile
    flavors:
      - metallic
      - berry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Artifexium
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: _Goobstation/Objects/Specific/Hydroponics/strange_berries.rsi
  - type: Produce
    seedId: strangeBerries
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Artifexium
        Quantity: 5

- type: entity
  name: "колода невкотти"
  description: "При посадці поза природним середовищем існування, вона виростає в зовсім іншу рослину."
  id: Nevcotta
  parent: ProduceBase
  components:
  - type: Sprite
    sprite: _Goobstation/Objects/Specific/Hydroponics/nevcotta.rsi
    state: icon
  - type: SolutionContainerManager
  - type: Produce
    seedId: towercap # Shhh, I don't want to make this an actual plant yet!
  - type: Log
    spawnedPrototype: NevcottaBark
    spawnCount: 2

- type: entity
  name: "кора невкотти"
  description: "Кора дерева Невкотта."
  id: NevcottaBark
  parent: BaseItem
  components:
  - type: Sprite
    sprite: _Goobstation/Objects/Specific/Hydroponics/nevcotta.rsi
    state: bark
  - type: Extractable
    grindableSolutionName: food
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: NevcottaPowder
          Quantity: 5
        - ReagentId: Fiber
          Quantity: 4


- type: entity
  name: "блюспейс помідор"
  parent: FoodBlueTomato
  id: FoodBluespaceTomato
  description: "Обережно з ним."
  components:
  - type: SwapTeleportOnThrow
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 3
        - ReagentId: Singulo
          Quantity: 5
        canReact: false
  - type: Sprite
    sprite: _Goobstation/Objects/Specific/Hydroponics/bluespace_tomato.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: bluespaceTomato
  - type: Extractable
    grindableSolutionName: food
    juiceSolution:
      reagents:
      - ReagentId: Singulo
        Quantity: 5
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 1
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: desecration
      - !type:SpillBehavior
        solution: food
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Tag
    tags:
    - Fruit
    - Vegetable
