- type: entity
  parent: BaseMachineCircuitboard
  id: StasisOperatingTableCircuitboard
  name: "плата стазисного операційного столу"
  description: "Машинна плата для стазисного операційного столу."
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: StasisOperatingTable
    stackRequirements:
      Cable: 6
      Silver: 2
      Steel: 6
      Manipulator: 2
