/// <summary>
/// Pirate psionics menu based on the Goob wanted menu.
/// </summary>

using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Systems;
using Content.Shared.Administration;
using Content.Shared.Dataset;
using Content.Shared.Psionics;
using Content.Shared.PsionicsRecords;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using System.Numerics;

namespace Content.Pirate.Client.PsionicsRecords;

[GenerateTypedNameReferences]
public sealed partial class PsionicsMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private readonly IPlayerManager _player;
    private readonly AccessReaderSystem _accessReader;
    private readonly IRobustRandom _random;
    private readonly SpriteSystem _spriteSystem;

	    [ValidatePrototypeId<DatasetPrototype>]
	    private const string ReasonPlaceholders = "PsionicsRecordsReasonPlaceholders";

    public Action<PsionicsStatus>? OnStatusSelected;
    public Action<PsionicsStatus, string>? OnDialogConfirmed;

    private PsionicsRecord? _selectedRecord;
    private DialogWindow? _reasonDialog;
    private bool _access;
    private EntityUid _uid;

    public PsionicsMenu(EntityUid uid, IRobustRandom robustRandom, AccessReaderSystem accessReader, IPlayerManager playerManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();
        _random = robustRandom;
        _accessReader = accessReader;
        _player = playerManager;
        _uid = uid;

        OnClose += () => _reasonDialog?.Close();

        foreach (var status in Enum.GetValues<PsionicsStatus>())
        {
            AddStatusSelect(status);
        }

        StatusOptionButton.OnItemSelected += args =>
        {
            SetStatus((PsionicsStatus)args.Id);
        };
    }

    public void UpdateState(PsionicsRecordsConsoleState state)
    {
        _access = _player.LocalSession?.AttachedEntity is {} player
                  && _accessReader.IsAllowed(player, _uid);
        if (!_access)
            return;

        if (state is { PsionicsRecord: not null, StationRecord: not null })
        {
            PopulateRecordContainer(state.StationRecord, state.PsionicsRecord);
            _selectedRecord = state.PsionicsRecord;
        }
        else
        {
            PersonName.Text = Loc.GetString("psionics-name-error");
            PersonJob.Text = Loc.GetString("psionics-job-error");
            PersonJobIcon.Texture = null;
            PsionicsReason.Visible = false;
            _selectedRecord = null;
            StatusOptionButton.Disabled = true;
        }
    }
	    private void PopulateRecordContainer(GeneralStationRecord stationRecord, PsionicsRecord psionicsRecord)
    {
        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/job_icons.rsi"), "Unknown");
        PersonName.Text = stationRecord.Name ?? "Unknown";
        PersonJob.Text = stationRecord.JobTitle ?? "Unknown";

	        if (_prototypeManager.TryIndex<JobIconPrototype>(stationRecord.JobIcon, out var proto))
	            PersonJobIcon.Texture = _spriteSystem.Frame0(proto.Icon);
	        if (psionicsRecord.Status != PsionicsStatus.None)
	            specifier = new SpriteSpecifier.Rsi(new ResPath("_EinsteinEngines/Interface/Misc/psionics_icons.rsi"), GetStatusIcon(psionicsRecord.Status));

        PersonStatusTX.SetFromSpriteSpecifier(specifier);
        PersonStatusTX.DisplayRect.TextureScale = new Vector2(3f, 3f);

        StatusOptionButton.SelectId((int)psionicsRecord.Status);
        if (psionicsRecord.Reason is { } reason)
        {
            var message = FormattedMessage.FromMarkupOrThrow(Loc.GetString($"psionics-records-console-{psionicsRecord.Status.ToString().ToLower()}-reason"));
            message.AddText($": {reason}");

            PsionicsReason.SetMessage(message);
            PsionicsReason.Visible = true;
        }
        else
        {
            PsionicsReason.Visible = false;
        }
    }
    private void AddStatusSelect(PsionicsStatus status)
    {
        var name = Loc.GetString($"psionics-records-status-{status.ToString().ToLower()}");
        StatusOptionButton.AddItem(name, (int)status);
    }
    private void SetStatus(PsionicsStatus status)
    {
        if (status == PsionicsStatus.Suspected
            || status == PsionicsStatus.Registered
            || status == PsionicsStatus.Abusing)
        {
            GetReason(status);
            return;
        }
        OnStatusSelected?.Invoke(status);
    }
    private void GetReason(PsionicsStatus status)
    {
        if (_reasonDialog != null)
        {
            _reasonDialog.MoveToFront();
            return;
        }

	        var field = "reason";
	        var title = Loc.GetString("psionics-records-status-" + status.ToString().ToLower());
	        var placeholders = _prototypeManager.Index<DatasetPrototype>(ReasonPlaceholders);
	        var placeholderValue = _random.Pick(placeholders.Values);
	        var placeholder = Loc.GetString("psionics-records-console-reason-placeholder", ("placeholder", placeholderValue));
	        var prompt = Loc.GetString("psionics-records-console-reason");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
        var entries = new List<QuickDialogEntry>() { entry };
        _reasonDialog = new DialogWindow(title, entries);

        _reasonDialog.OnConfirmed += responses =>
        {
            var reason = responses[field];
            if (reason.Length < 1 || reason.Length > 256)
                return;

            OnDialogConfirmed?.Invoke(status, reason);
        };

        _reasonDialog.OnClose += () => { _reasonDialog = null; };
    }

    private string GetStatusIcon(PsionicsStatus status)
    {
        return status switch
        {
            PsionicsStatus.Suspected => "hud_suspected",
            PsionicsStatus.Registered => "hud_registered",
            PsionicsStatus.Abusing => "hud_abusing",
            _ => "PsionicsIconStatus"
        };
    }
}

