# SPDX-FileCopyrightText: 2025 Arraydeess <arraygitbash@gmail.com>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseItem
  id: BalloonPackageBasic
  name: "набір кульок"
  description: "Пакунок, що містить одну випадкову кульку."
  components:
  - type: Sprite
    sprite: _Goobstation/Objects/Fun/balloon_package.rsi
    state: icon
  - type: Item
    size: Tiny
  - type: SpawnItemsOnUse
    items:
    - id: RedBalloon
      orGroup: BalloonRandom
      prob: 0.33 # Lower tier rarer
    - id: BlueBalloon
      orGroup: BalloonRandom
      prob: 0.4
    - id: GreenBalloon
      orGroup: BalloonRandom
    - id: YellowBalloon
      orGroup: BalloonRandom
    - id: PinkBalloon
      orGroup: BalloonRandom
    - id: WhiteBalloon
      orGroup: BalloonRandom # higher tier balloons are rarer
      prob: 0.4
    - id: BlackBalloon
      orGroup: BalloonRandom
      prob: 0.4
    - id: SteelBalloon
      orGroup: BalloonRandom
      prob: 0.33
    - id: ZebraBalloon
      orGroup: BalloonRandom
      prob: 0.33
    - id: RainbowBalloon
      orGroup: BalloonRandom
      prob: 0.2
    - id: CeramicBalloon
      orGroup: BalloonRandom
      prob: 0.1
    sound:
      path: /Audio/Effects/unwrap.ogg

- type: entity
  parent: BaseItem
  id: BalloonPackagePremium
  name: "преміум-набір кульок"
  description: "Пакунок, що містить одну випадкову кульку."
  components:
  - type: Sprite
    sprite: _Goobstation/Objects/Fun/balloon_package.rsi
    state: gold
  - type: Item
    size: Tiny
  - type: SpawnItemsOnUse
    items:
    - id: BlackBalloon
      orGroup: BalloonRandom
    - id: WhiteBalloon
      orGroup: BalloonRandom
    - id: SteelBalloon
      orGroup: BalloonRandom
      prob: 0.7
    - id: ZebraBalloon
      orGroup: BalloonRandom
      prob: 0.65 #65 chance 65 65 65
    - id: RainbowBalloon
      orGroup: BalloonRandom
      prob: 0.5
    - id: CeramicBalloon
      orGroup: BalloonRandom # higher tier balloons are rarer
      prob: 0.4
    # This fucking kills server performance
    # - id: MoabBalloon
    #   orGroup: BalloonRandom
    #   prob: 0.10
    # - id: BfbBalloon
    #   orGroup: BalloonRandom
    #   prob: 0.05
    # - id: ZomgBalloon
    #   orGroup: BalloonRandom
    #   prob: 0.01
    sound:
      path: /Audio/Effects/unwrap.ogg


- type: entity
  name: "коробка з пакунками кульок"
  parent: BoxCardboard
  id: BoxBalloonPackage
  description: "Коробка, повна майбутніх кульок."
  components:
  - type: StorageFill
    contents:
      - id: BalloonPackageBasic
        amount: 9
  - type: Sprite
    sprite: _Goobstation/Objects/Storage/boxes.rsi

- type: entity
  name: "коробка преміум-набору кульок"
  parent: BoxCardboard
  id: PremiumBoxBalloonPackage
  description: "Коробка, повна майбутніх кульок."
  components:
  - type: StorageFill
    contents:
      - id: BalloonPackagePremium
        amount: 9
  - type: Sprite
    sprite: _Goobstation/Objects/Storage/boxes.rsi


- type: entity
  id: CrateBalloonPackage
  parent: CratePlastic
  name: "пакунок для лопання кульок"
  description: "Ящик, що містить 2 повні коробки з кульками та додаткове обладнання для їх лопання."
  components:
  - type: StorageFill
    contents:
    - id: BoxBalloonPackage
      amount: 2
    - id: ClothingOuterSuitMonkey
      amount: 1
    - id: Dart
      amount: 1
    - id: MonkeyCube
      prob: 0.7
    # Extra
    - id: MonkeyCube
      prob: 0.4


- type: entity
  id: PremiumCrateBalloonPackage
  parent: CratePirate
  name: "преміум-набір воїна проти кульок"
  description: "Містить найелітніші кульки та додаткове спорядження для лускання. УВАГА! НАБЛИЖАЮТЬСЯ КІЛЬКА КУЛЬОК КЛАСУ MOAB!"
  components:
  - type: StorageFill
    contents:
    - id: PremiumBoxBalloonPackage
      amount: 1
    - id: ClothingOuterSuitMonkey
      amount: 1
    - id: boomerang
      amount: 1
    - id: MonkeyCube
      prob: 0.7
    - id: ClothingOuterSuitMonkey   # Extra
      amount: 1
      prob: 0.4
    - id: MonkeyCube
      prob: 0.4
